#site config
theme: jekyll-theme-slate
title: Jody Smith
description: Hi, I'm Jody. I am an IT director and learning technology consultent. I am passionate about all things tech related, with a special interest in front end development and distributed learning.
